version: '3'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    networks:
      - ollama-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  translator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: translator
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_URL=http://ollama:11434/api/generate
      - OLLAMA_MODEL=mistral
      - PORT=3008
    ports:
      - "3008:3008"
    restart: unless-stopped
    networks:
      - ollama-network

volumes:
  ollama_data:

networks:
  ollama-network:
    driver: bridge